### ISSUE TITLE
'Title' of a note getting superimposed on the 'date'

### ISSUE THREAD

**Issue by csdali13** [Sharkgrammer/notes-app#1]
I was just testing the app, and when I saved a note with a pretty long title, it gets superimposed with the date. Attached a screenshot of the issue.
![note title getting superimposed on date](https://user-images.githubusercontent.com/46881275/53622144-f6f5dd80-3c4c-11e9-886c-272797e9881b.png)

It would be better to show longer titles with ellipsis (...) and when we hover the mouse over, we could show the full title as a tool tip text pop-up.

**Comment by Sharkgrammer** [comment]
I never actually wrote anything to deal with that as most of the tiles i used when testing were very small. Thank you for letting me know though, i'll fix it up this evening.
